version: 1

snapshots:
  - name: snapshot_dim_stop
    description: >
      Snapshot of the dim_stop table to track changes in stop location, administrative regions, and proximity to schools.
      Uses check-based strategy to record only real changes to selected fields.
    columns:
      - name: stop_id
        description: Unique identifier of the stop.
        tests:
          - not_null
      - name: stop_name
        description: Human-readable name of the stop.
      - name: stop_latitude
        description: Latitude coordinate of the stop.
      - name: stop_longitude
        description: Longitude coordinate of the stop.
      - name: municipality_id
        description: Identifier of the municipality the stop belongs to.
      - name: municipality_name
        description: Name of the municipality the stop belongs to.
      - name: region_id
        description: Region identifier for the stop.
      - name: region_name
        description: Region name for the stop.
      - name: near_school
        description: Boolean flag indicating if the stop is near a school.
      - name: ingested_at
        description: Timestamp of ingestion; included for traceability, not used in snapshot diff logic.
      - name: dbt_scd_id
        description: Unique identifier for each version of the snapshot record (generated by dbt).
      - name: dbt_valid_from
        description: Timestamp when this version of the record became valid.
      - name: dbt_valid_to
        description: Timestamp when this version of the record became invalid (null if still valid).

  - name: snapshot_dim_line
    description: >
      Snapshot of the dim_line table, at route-level granularity.
      Tracks changes to routes and associated line definitions over time, including metadata like circular routes and school services.
    columns:
      - name: route_id
        description: Unique identifier for the route.
        tests:
          - not_null
      - name: route_long_name
        description: Full name of the route.
      - name: route_short_name
        description: Short identifier (e.g., number or label) of the route.
      - name: route_type
        description: Type of route.
      - name: route_color
        description: Color used for route display.
      - name: route_text_color
        description: Color of text used on route display.
      - name: line_id
        description: Associated line identifier.
      - name: line_long_name
        description: Full name of the line.
      - name: line_short_name
        description: Short name or code of the line.
      - name: line_type
        description: Type/category of the line.
      - name: agency_id
        description: Identifier of the transport agency responsible for the route.
      - name: tts_name
        description: Text-to-speech formatted name for the line or route.
      - name: circular
        description: Boolean flag indicating if the route is circular.
      - name: school
        description: Boolean flag indicating if the route is school-specific.
      - name: ingested_at
        description: Timestamp when this record was ingested into the data pipeline.
      - name: dbt_scd_id
        description: Unique identifier for each version of the snapshot record (generated by dbt).
      - name: dbt_valid_from
        description: Timestamp when this version of the record became valid.
      - name: dbt_valid_to
        description: Timestamp when this version of the record became invalid (null if still valid).

  - name: snapshot_dim_trip
    description: >
      Snapshot of the dim_trip table, tracking changes in scheduled trips over time,
      including route, direction, and pattern assignments.
    columns:
      - name: trip_id
        description: Unique identifier of the trip.
        tests:
          - not_null
      - name: direction
        description: Direction of the trip (e.g., 0 or 1).
      - name: route_id
        description: Identifier of the route the trip belongs to.
      - name: service_id
        description: Identifier of the service.
      - name: trip_headsign
        description: Destination or label displayed to passengers.
      - name: pattern_id
        description: Identifier of the pattern associated with the trip.
      - name: shape_id
        description: Identifier for the shape/path of the trip.
      - name: ingested_at
        description: Timestamp of ingestion; included for traceability only.
      - name: dbt_scd_id
        description: Unique identifier for each version of the snapshot record (generated by dbt).
      - name: dbt_valid_from
        description: Timestamp when this version of the record became valid.
      - name: dbt_valid_to
        description: Timestamp when this version of the record became invalid (null if still valid).