SELECT
  stop_id,
  stop_code,
  stop_name,
  stop_short_name,
  tts_stop_name,
  parent_station,
  platform_code,
  location_type,
  stop_latitude,
  stop_longitude,
  region_id,
  region_name,
  district_id,
  district_name,
  municipality_id,
  municipality_name,
  parish_id,
  parish_name,
  REPLACE(REPLACE(locality_id, 'NaN', 'N/A'), 'UNKNOWN', 'N/A') AS locality_id,
  REPLACE(REPLACE(locality, 'NaN', 'N/A'), 'UNKNOWN', 'N/A') AS locality,
  jurisdiction,
  areas,
  wheelchair_boarding,
  REPLACE(REPLACE(has_sidewalk, 'NaN', 'N/A'), 'UNKNOWN', 'N/A') AS has_sidewalk,
  sidewalk_type,
  REPLACE(REPLACE(has_crossing, 'NaN', 'N/A'), 'UNKNOWN', 'N/A') AS has_crossing,
  REPLACE(REPLACE(has_flat_access, 'NaN', 'N/A'), 'UNKNOWN', 'N/A') AS has_flat_access,
  REPLACE(REPLACE(has_wide_access, 'NaN', 'N/A'), 'UNKNOWN', 'N/A') AS has_wide_access,
  REPLACE(REPLACE(has_tactile_access, 'NaN', 'N/A'), 'UNKNOWN', 'N/A') AS has_tactile_access,
  REPLACE(REPLACE(has_abusive_parking, 'NaN', 'N/A'), 'UNKNOWN', 'N/A') AS has_abusive_parking,
  last_accessibility_maintenance,
  last_accessibility_check,
  REPLACE(REPLACE(has_pole, 'NaN', 'N/A'), 'UNKNOWN', 'N/A') AS has_pole,
  REPLACE(REPLACE(has_cover, 'NaN', 'N/A'), 'UNKNOWN', 'N/A') AS has_cover,
  REPLACE(REPLACE(has_shelter, 'NaN', 'N/A'), 'UNKNOWN', 'N/A') AS has_shelter,
  REPLACE(REPLACE(shelter_code, 'NaN', 'N/A'), 'UNKNOWN', 'N/A') AS shelter_code,
  REPLACE(REPLACE(shelter_maintainer, 'NaN', 'N/A'), 'UNKNOWN', 'N/A') AS shelter_maintainer,
  REPLACE(REPLACE(has_mupi, 'NaN', 'N/A'), 'UNKNOWN', 'N/A') AS has_mupi,
  REPLACE(REPLACE(has_bench, 'NaN', 'N/A'), 'UNKNOWN', 'N/A') AS has_bench,
  REPLACE(REPLACE(has_trash_bin, 'NaN', 'N/A'), 'UNKNOWN', 'N/A') AS has_trash_bin,
  REPLACE(REPLACE(has_lighting, 'NaN', 'N/A'), 'UNKNOWN', 'N/A') AS has_lighting,
  REPLACE(REPLACE(has_electricity, 'NaN', 'N/A'), 'UNKNOWN', 'N/A') AS has_electricity,
  REPLACE(REPLACE(docking_bay_type, 'NaN', 'N/A'), 'UNKNOWN', 'N/A') AS docking_bay_type,
  last_infrastructure_maintenance,
  last_infrastructure_check,
  REPLACE(REPLACE(has_flag, 'NaN', 'N/A'), 'UNKNOWN', 'N/A') AS has_flag,
  flag_maintainer,
  REPLACE(REPLACE(has_pip_static, 'NaN', 'N/A'), 'UNKNOWN', 'N/A') AS has_pip_static,
  REPLACE(REPLACE(has_pip_audio, 'NaN', 'N/A'), 'UNKNOWN', 'N/A') AS has_pip_audio,
  pip_audio_code,
  REPLACE(REPLACE(has_pip_realtime, 'NaN', 'N/A'), 'UNKNOWN', 'N/A') AS has_pip_realtime,
  pip_realtime_code,
  REPLACE(REPLACE(has_h2oa_signage, 'NaN', 'N/A'), 'UNKNOWN', 'N/A') AS has_h2oa_signage,
  REPLACE(REPLACE(has_schedules, 'NaN', 'N/A'), 'UNKNOWN', 'N/A') AS has_schedules,
  REPLACE(REPLACE(has_tactile_schedules, 'NaN', 'N/A'), 'UNKNOWN', 'N/A') AS has_tactile_schedules,
  REPLACE(REPLACE(has_network_map, 'NaN', 'N/A'), 'UNKNOWN', 'N/A') AS has_network_map,
  last_schedules_maintenance,
  last_schedules_check,
  near_health_clinic,
  near_hospital,
  near_university,
  near_school,
  near_police_station,
  near_fire_station,
  near_shopping,
  near_historic_building,
  near_transit_office,
  near_beach,
  subway,
  light_rail,
  train,
  boat,
  airport,
  bike_sharing,
  bike_parking,
  car_parking,
  line_id,
  pattern_id,
  route_id,
  REPLACE(REPLACE(facility_id, 'NaN', 'N/A'), 'NA', 'N/A') AS facility_id,
  stop_url,
  operational_status,
  _endpoint,
  _source_file,
  ingested_at
FROM {{ source('carris_transformations', 'staging_stops_exploded') }}