# Name of the project
name: 'carris_transformations'
version: '1.0.0'

# Configuration of the "profile" dbt uses for this project.
profile: 'carris_transformations'

# Specific configurations that define where dbt should look for different types of files within the project.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directories to be removed by `dbt clean`
clean-targets:         
  - "target"
  - "dbt_packages"

# In this configuration example, we instruct dbt to build all models in the example/
# directory as views by default. These settings can be overridden in individual model
# files using the `{{ config(...) }}` macro.
models:
  carris_transformations:
    # Config indicated by + and applies to all files under models/marts and models/staging
    staging:
      +materialized: view
    marts:
      +materialized: table
