carris_transformations:
  target: "{{ env_var('TARGET') }}"
  outputs:
    prod:
      dataset: applied_project_mart_grupo_1
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: europe-west1
      method: oauth
      priority: interactive
      project: "{{ env_var('PROJECT_ID') }}"
      threads: 4
      type: bigquery
    dev:
      dataset: applied_project_mart_grupo_1_dev
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: europe-west1
      method: oauth
      priority: interactive
      project: "{{ env_var('PROJECT_ID') }}"
      threads: 4
      type: bigquery